"*.{json,yml}":
  - eslint --fix
  - cspell lint --no-progress --show-suggestions --show-context --no-must-find-files --dot

"*.?([cm])[jt]s?(x)":
  - eslint --fix
  - cspell lint --no-progress --show-suggestions --show-context --no-must-find-files --dot

"src/**/*.?([cm])[jt]s?(x)":
  - tsc-files -p src/tsconfig.json --noEmit

"./*.?([cm])[jt]s?(x)":
  - tsc-files -p tsconfig.json --noEmit

"*.md":
  - markdownlint-cli2 --fix
  - eslint --fix
  - cspell lint --no-progress --show-suggestions --show-context --no-must-find-files --dot

pnpm-lock.yaml:
  - "pnpm dedupe && :"
