"*.{json,yml}":
  - eslint --fix
  - cspell lint --no-progress --show-suggestions --show-context --no-must-find-files --dot

"*.ts":
  - eslint --fix
  - cspell lint --no-progress --show-suggestions --show-context --no-must-find-files --dot
  - tsc-files -p tsconfig.build.json --noEmit

"*.md":
  - eslint --fix
  - markdownlint --config=.markdownlint.json --ignore-path=.markdownlintignore
  - cspell lint --no-progress --show-suggestions --show-context --no-must-find-files --dot

"pnpm-lock.yaml":
  - "pnpm dedupe && :"
