"$schema": http://json.schemastore.org/prettierrc

plugins:
  - prettier-plugin-packagejson

trailingComma: "all"

overrides:
  - files: "*.md"
    options:
      embeddedLanguageFormatting: "off"
  - files: ".nvmrc"
    options:
      parser: "yaml"
