name: Prepare
description: Prepares the repo for a typical CI job

inputs:
  node-version:
    required: false
    description: "`node-version` passed to `actions/setup-node`."
    default: "latest"

runs:
  using: "composite"
  steps:
    - name: Configure Git
      run: |
        git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
        git config --global user.name ${GITHUB_ACTOR}
      shell: bash
    - uses: pnpm/action-setup@0e279bb959325dab635dd2c09392533439d90093 # v6
    - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
      with:
        node-version: ${{ inputs.node-version }}
        cache: "pnpm"
    - run: pnpm install --frozen-lockfile --ignore-scripts
      shell: bash
