name: Prepare
description: Prepares the repo for a typical CI job

inputs:
  node-version:
    required: false
    description: "`node-version` passed to `actions/setup-node`."
    default: "latest"

runs:
  using: "composite"
  steps:
    - name: Configure Git
      run: |
        git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
        git config --global user.name ${GITHUB_ACTOR}
      shell: bash
    - uses: pnpm/action-setup@b906affcce14559ad1aafd4ab0e942779e9f58b1 # v4
    - uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6
      with:
        node-version: ${{ inputs.node-version }}
        cache: "pnpm"
    - run: pnpm install --frozen-lockfile --ignore-scripts
      shell: bash
