name: Prepare
description: Prepares the repo for a typical CI job

inputs:
  node-version:
    required: false
    description: "`node-version` passed to `actions/setup-node`."
    default: "latest"

runs:
  using: "composite"
  steps:
    - name: Configure Git
      run: |
        git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
        git config --global user.name ${GITHUB_ACTOR}
      shell: bash
    - uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4
    - uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6
      with:
        node-version: ${{ inputs.node-version }}
        cache: "pnpm"
    - run: pnpm install --frozen-lockfile --ignore-scripts
      shell: bash
