name: Build Docs

on:
  pull_request:
  workflow_dispatch:
  workflow_call:

jobs:
  build_node:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/prepare
      - run: pnpm run build:node
      - run: pnpm run build:docs
