name: Lint Knip

on:
  pull_request:
  workflow_dispatch:
  workflow_call:

jobs:
  lint_knip:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/prepare
      - run: pnpm run lint:knip
