name: Lint Knip (Development)

on:
  pull_request:
  workflow_dispatch:
  workflow_call:

jobs:
  lint_knip_dev:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/prepare
      - run: pnpm run lint:knip:development
