name: Lint Markdown

on:
  pull_request:
  workflow_dispatch:
  workflow_call:

jobs:
  lint_markdown:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/prepare
      - run: pnpm run build:node
      - run: pnpm run lint:md-full
