name: "Semantic PR"

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize

jobs:
  main:
    name: Validate PR title
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v5.5.3
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          types: |
            feat
            fix
            perf
            refactor
            style
            docs
            test
            build
            ci
            chore
            part
          scopes: |
            functional-parameters
            immutable-data
            no-classes
            no-class-inheritance
            no-conditional-statements
            no-expression-statements
            no-let
            no-loop-statements
            no-mixed-types
            no-promise-reject
            no-return-void
            no-this-expressions
            no-throw-statements
            no-try-statements
            prefer-immutable-types
            prefer-property-signatures
            prefer-readonly-types
            prefer-tacit
            readonly-type
            type-declaration-immutability
            deps
            dev-deps
            peer-deps
            release-patch
            release-minor
            release-major
          requireScope: false
          subjectPattern: ^(?![A-Z]).+$ # Don't start with an uppercase character.
          subjectPatternError: |
            The subject "{subject}" should not start with an uppercase character.
          headerPattern: '^(\w*)(?:\(([\w$.\-*/ ]*)\))?!?: (.*)$'
          headerPatternCorrespondence: type, scope, subject
