name: Sync labels

on:
  push:
    branches:
      - main
    paths:
      - .github/labels.yml
  workflow_dispatch:

permissions:
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - uses: micnncim/action-label-syncer@3abd5ab72fda571e69fffd97bd4e0033dd5f495c # v1
        with:
          manifest: .github/labels.yml
        env:
          GITHUB_TOKEN: ${{ github.token }}
